# Build CI workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Validate wrapper to prevent potential supply chain attack
  gradle-wrapper-validation:
    runs-on: ubuntu-latest

    name: Validate Gradle wrapper

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5

  build:
    runs-on: ubuntu-latest

    name: Java build

    steps:
      - uses: actions/checkout@v5

      # Set JDK
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build
      - name: Build with Gradle
        run: ./gradlew build
